[package]
name = "brawl_exporter"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]

[dependencies]
brawllib_rs = { path = "../brawllib_rs" }
cgmath = "0.16"
pf_sandbox = { path = "/home/rubic/Projects/Smash/pf_sandbox/pf_sandbox/pf_sandbox" }
treeflection = "0.1"
ref_slice = "1"

[patch.crates-io]
gilrs = { git = "https://gitlab.com/rukai/gilrs", branch = "pf_sandbox2" }
vulkano = { git = "https://github.com/rukai/vulkano", branch = "pf_sandbox2" }
vulkano-win = { git = "https://github.com/rukai/vulkano", branch = "pf_sandbox2" }
vulkano-shader-derive = { git = "https://github.com/rukai/vulkano", branch = "pf_sandbox2" }
vulkano_text = { git = "https://github.com/rukai/vulkano-text", branch = "pf_sandbox2" }
