[package]
name = "brawl_exporter"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]

[dependencies]
brawllib_rs = { path = "../brawllib_rs" }
cgmath = "0.16"
enum_traits = "0.3"
pf_sandbox = { path = "/home/rubic/Projects/Smash/pf_sandbox/pf_sandbox/pf_sandbox" }
ref_slice = "1"
treeflection = "0.1"
getopts = "0.2"
env_logger = "0.5"
log = "0.4"
noisy_float = "0.1"
